name: codesearch-cli
base: core24
adopt-info: codesearch-cli
summary: Debian Code Search CLI tool
description: |
  Command-line tool for codesearch.debian.net

grade: stable
confinement: strict

environment:
  PYTHONPATH: $SNAP/debian_codesearch_client:$SNAP/usr/lib/python3/dist-packages
  PYTHONIOENCODING: utf-8

apps:
  codesearch-cli:
    command: bin/codesearch
    plugs:
      - network

parts:
  codesearch-cli:
    plugin: python
    source: https://salsa.debian.org/debian/codesearch-cli
    source-type: git
    stage-packages:
      - python3-requests
      - python3-websocket
    override-build: |
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/0001-HACK-support-setting-host-URI-via-an-environment-var.patch
      snapcraftctl build
      snapcraftctl set-version "$(git describe --all --long | sed 's|heads/||')"
