name: codesearch-cli
base: core20
adopt-info: codesearch-cli
summary: Debian Code Search CLI tool
description: |
  Command-line tool for codesearch.debian.net

grade: stable
confinement: strict

environment:
  PYTHONPATH: $SNAP/dcs_python_client:$SNAP/usr/lib/python3/dist-packages
  PYTHONIOENCODING: utf-8

apps:
  codesearch-cli:
    command: codesearch_cli.py
    plugs:
      - network

parts:
  codesearch-cli:
    plugin: dump
    source: https://salsa.debian.org/debian/codesearch-cli
    source-type: git
    stage-packages:
      - python3-requests
      - python3-websocket
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(git describe --all --long | sed 's|heads/||')"
